language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
before_install:
    - "cpanm Mojolicious Protocol::WebSocket AnyEvent JSON Scalar::Util"
    - "cpanm Devel::Cover::Report::Coveralls"
script:
  perl Makefile.PL && make test && cover -test -report coveralls
